config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get '/about', to: 'home#about'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts, only: [:index,:new,:create,:destroy]
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }, 
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  #文字列をハッシュ化する
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  #トークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  #永続セッションのためにユーザーをDBに保存
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  #引数のトークンがダイジェストと一致いたらtrue
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーのフォローを解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  #フォローしているユーザーの投稿を取得
  def feed
    following_ids = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
    Post.where("user_id IN (#{following_ids}) OR user_id= :user_id",user_id: id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy,
                                        :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page], per_page: 5)
  end


  def new
    @user = User.new
  end

  def create
    @user = User.new(
      name: params[:name],
      email: params[:email],
      password: params[:password],
      password_confirmation: params[:password_confirmation],
    )
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Rails App!"
      redirect_to user_url(@user)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.name = params[:name]
    @user.email = params[:email]
    @user.password = params[:password]
    @user.password_confirmation = params[:password_confirmation]

    if params[:image_name]
      @user.image_name = "#{@user.id}.png"
      image = params[:image_name]
      File.binwrite("public/user_images/#{@user.image_name}", image.read)
    end

    if @user.save
      flash[:notice] = "ユーザー情報を編集しました"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page], per_page: 10)
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page], per_page: 10)
    render 'show_follow'
  end

  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn", id: "follow" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-unfollow", id: "follow" %>
<% end %>

app/views/users/_users.html.erb
<% @users.each do |user| %>
  <li>
    <%= image_tag "/user_images/#{user.image_name}", alt: "user icon", id:"user-icon" %>
    <%= link_to user.name, user_path(user), class: "user-name" %>
    <% if current_user.admin? && !(user == current_user) %>
      | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
    <% end %>
  </li>
<% end %>

app/views/users/edit.html.erb
<h1>ユーザー情報を変更する</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name, "名前" %>
      <%= f.text_field :name, name: "name", class: 'form-control' %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, name: "email", class: 'form-control' %>

      <%= f.label :image_name, "プロフィール画像" %>
      <%= f.file_field :image_name, name: "image_name", class: 'form-control' %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, name: "password", class: 'form-control' %>

      <%= f.label :password_cofirmation, "パスワード確認" %>
      <%= f.password_field :password_cofirmation, name: "password_confirmation", class: 'form-control' %>

      <%= f.submit "変更する", class: "btn" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>

<%= will_paginate @users, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= image_tag "/user_images/#{user.image_name}", alt: "user icon", id:"user-icon" %>
      <%= link_to user.name, user_path(user), class: "user-name" %>
      <% if current_user.admin? && !(user == current_user) %>
        | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= will_paginate @users, :previous_label => ' &lt 前へ', :next_label => '次へ &gt'%>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name, "名前" %>
      <%= f.text_field :name, name: "name", class: 'form-control' %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, name: "email", class: 'form-control' %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, name: "password", class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワード確認" %>
      <%= f.password_field :password_confirmation, name: "password_confirmation", class: 'form-control' %>

      <%= f.submit "アカウント登録", class:"btn" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user-info">
      <h1>
        <%= image_tag "/user_images/#{@user.image_name}", alt: "user icon", id:"user-icon" %>
        <%= @user.name %> 
      </h1>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
    <%= render 'follow_form' if logged_in? %>
  </aside>
  <div class="col-md-8">
    <h3>投稿 (<%= @user.posts.count %>)</h3>
    <% if @user.posts.any? %>
      <ol class="posts">
        <%= render @posts %>
      </ol>
      <%= will_paginate @posts, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
      <%= image_tag "/user_images/#{@user.image_name}", alt: "user icon", id:"user-icon" %>
      <%= @user.name %>
      </h1>
      <span><%= link_to "プロフィール", @user, class: "my-view" %></span>
      <span><b>投稿:</b> <%= @user.posts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <h2><%= @title %></h2>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render 'users' %>
      </ul>
      <%= will_paginate @users, :previous_label => ' &lt 前へ', :next_label => '次へ &gt'  %>
    <% end %>
  </div>
</div>