config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get '/about', to: 'home#about'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts, only: [:index,:new,:create,:destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <% if logged_in? %>
      <%= link_to "Diary", posts_path, id: "logo" %>
    <% else %>
      <%= link_to "Diary", root_path, id: "logo" %>
    <% end %>
    <nav class="nav navbar-nav navbar-right">
      <% if logged_in? %>
        <li><%= link_to "投稿一覧", posts_path %></li>
        <li><%= link_to "ユーザー一覧", users_path %></li>
        <li><%= link_to "新規投稿", new_post_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            アカウント<b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "マイページ", user_path(current_user) %></li>
            <li><%= link_to "設定", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Diaryとは", about_path %></li>
        <li><%= link_to "ログイン", login_path %></li>
      <% end %>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diary</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    </div>
  </body>
</html>